Advanced help
wwosimulation/Narrator-bot pull request #135
Opened 2021-08-24 11:18 UTC by Hackante

<h1>Advanced Help Command</h1>
<h3>Features</h3>

1. You can now get more information about a command like usage or description. If there are aliases you can also see those.
2. There is a list of arguments you can use in commands.

<h3>Usages</h3>

Help for another command:
`+help command`
Help for arguments:
`+help args`

2021-08-29 15:30 UTC, Hackante commented
What do you want me to change? If I'm correct everything works fine and is able to be merged

2021-08-29 16:17 UTC, thewilloftheshadow commented
I didn't realize you were done, sorry

2021-08-29 20:02 UTC, thewilloftheshadow requested changes
Looks great, just a couple small adjustments

2021-08-29 20:02 UTC, thewilloftheshadow commented on commands/bot/help.js
> +            embed
Can you add the icon here too for consistency?

2021-08-29 20:08 UTC, Hackante commented on commands/bot/help.js
> +                .setDescription(
edited in vs code

2021-08-29 21:56 UTC, Hackante commented
OMG it's finally able to merge!

2021-08-30 14:27 UTC, Hackante commented
Changes done and added description and usage for settings.js. Please look over it once again. then it's done

2021-08-30 15:36 UTC, thewilloftheshadow approved these changes

2021-08-30 15:36 UTC, merged