MessageX class removal
wwosimulation/Narrator-bot pull request #316
Opened 2022-03-31 00:19 UTC by 3061LRTAGSPKJMORMRT

- Removed the usage of the MessageEmbed, MessageButton, MessageSelectMenu, MessageActionRow class
- Discord.js v14 has renamed these, and it will be more work then, so why not start slowly now
- Moreover, we will have to require builders when doing so. Using objects is way better
- These classes return an object, so I converted it
- Please note that for embed colors, they will take a `Number` instead of a `hex string`.
- Use the `resolveColor` method that is imported from the `Util` class to convert names or the `RANDOM` color
- For components, they will have a `type` property
   * Type `1` is for Action Rows
   * Type `2` is for Buttons
   * Type `3` is for Select Menus

2022-03-31 02:14 UTC, thewilloftheshadow submitted a review, later dismissed
This needs a [rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase)

2022-03-31 06:04 UTC, 3061LRTAGSPKJMORMRT commented
> This needs a [rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase)

How do I do a rebase on a fork tho

2022-03-31 06:16 UTC, Hackante commented
maybe `git rebase <Iink of repo>`

2022-03-31 06:53 UTC, 3061LRTAGSPKJMORMRT commented
> maybe `git rebase <Iink of repo>`

It keeps saying it's up to date

2022-03-31 07:23 UTC, 3061LRTAGSPKJMORMRT commented
Okay i ___think___ i did it.

2022-03-31 16:03 UTC, Hackante requested changes
There are more embeds in 
- ./server.js:248
- ./commands/bot/roleinfo.js:10
- ./commands/game/flee.js:27 ,  ./commands/game/flee.js:41

2022-03-31 16:05 UTC, thewilloftheshadow commented on commands/bot/botinfo.js
> +            value: `Bot Host, Retired Lead Developer: <@439223656200273932>\n` + `Lead Developer: Hackante#1482\n` + `Originally created by: Ashish#0540\n` + `Beta Testers: <@!159717599993790464> <@!
Removed what? Now you have staff on there twice

2022-04-01 15:12 UTC, Hackante requested changes
Still two embeds in flee.js
then you are good to go ig

2022-04-01 15:12 UTC, Hackante commented on server.js
>                                  color: "GREEN",
```suggestion
                                color: 0x00ff00,
```

2022-04-02 08:42 UTC, Hackante requested changes

2022-04-02 08:42 UTC, Hackante commented on commands/game/flee.js
>                          })
```suggestion
                        }
```

2022-04-02 09:02 UTC, Hackante approved these changes

2022-04-02 09:03 UTC, merged