This is for collecting data
wwosimulation/Narrator-bot pull request #438
Opened 2022-10-29 09:58 UTC by Gorott

just for collecting data nothing else

DO NOT DELETE BRANCH!!!!!!!!!!!!!!!!!!

2022-10-29 11:22 UTC, Hackante requested changes

2022-10-29 11:22 UTC, Hackante commented on events/slashCmds.js
> +        console.log("ello")
Do you still need them for debugging?

2022-10-29 11:22 UTC, Hackante commented on commands/economy/profile.js
> +/*const { players } = require("../../db.js")
remove the comment or is the profile command not working anymore? 🤔

2022-10-29 11:22 UTC, Hackante commented on server.js
> +client.login(process.env.TOKENs)
Is that for beta .env ?

2022-10-29 11:22 UTC, Hackante commented on server.js
> +    // client.channels.cache.get("832884582315458570").send(`Bot has started, running commit \`${commit}\` on branch \`${branch}\``)
You can add that again if that doesn't cause any errors

2022-10-29 11:22 UTC, Hackante commented on server.js
> +                    console.log(client.slashCommands)
For debugging?

2022-10-29 11:22 UTC, Hackante commented on package.json
> -        "canvas": "^2.9.0",
When you add the profile command also add canvas again

2022-10-30 10:55 UTC, Gorott commented
made the changes

2022-10-30 13:50 UTC, Hackante approved these changes

2022-10-30 13:50 UTC, merged